#!/bin/bash
DOTFILES_DIR="$HOME/dotfiles"
ln -snf "$DOTFILES_DIR/zsh/.zshrc" "$HOME/.zshrc"
ln -snf "$DOTFILES_DIR/tmux/.tmux.conf" "$HOME/.tmux.conf"
ln -snf "$DOTFILES_DIR/shell/.profile" "$HOME/.profile"
ln -snf "$DOTFILES_DIR/git/.gitconfig" "$HOME/.gitconfig"
mkdir -p "$HOME/.config"
ln -snf "$DOTFILES_DIR/wezterm/.config/wezterm" "$HOME/.config/wezterm"
ln -snf "$DOTFILES_DIR/.config/nvim" "$HOME/.config/nvim"
ln -snf "$DOTFILES_DIR/p10k/.p10k.zsh" "$HOME/.p10k.zsh"
mkdir -p "$HOME/.config/fastfetch"
ln -snf "$DOTFILES_DIR/fastfetch/config.jsonc" "$HOME/.config/fastfetch/config.jsonc"
mkdir -p "$HOME/.local/share/applications"
ln -snf "$DOTFILES_DIR/applications/org.wezfurlong.wezterm.desktop" "$HOME/.local/share/applications/org.wezfurlong.wezterm.desktop"
mkdir -p "$HOME/.config/wofi"
ln -snf "$DOTFILES_DIR/wofi/config" "$HOME/.config/wofi/config"
ln -snf "$DOTFILES_DIR/wofi/style.css" "$HOME/.config/wofi/style.css"
mkdir -p "$HOME/.local/share/libskk/rules/myrule/keymap"
ln -snf "$DOTFILES_DIR/skk/metadata.json" "$HOME/.config/libskk/rules/myrule/metadata.json"
ln -snf "$DOTFILES_DIR/skk/keymap/hiragana.json" "$HOME/.config/libskk/rules/myrule/keymap/hiragana.json"
ln -snf "$DOTFILES_DIR/skk/keymap/katakana.json" "$HOME/.config/libskk/rules/myrule/keymap/katakana.json"
sudo mkdir -p "/etc/sddm.conf.d"
sudo ln -snf "$DOTFILES_DIR/dotfiles/sddm/theme.conf" "/etc/sddm.conf.d/theme.conf"
sudo ln -snf "$DOTFILES_DIR/dotfiles/sddm/Suger-Candy/theme.conf" "/usr/share/sddm/themes/Sugar-Candy/theme.conf"
sudo ln -snf "$DOTFILES_DIR/dotfiles/assets/lock/angel.png" "/usr/share/sddm/Sugar-Candy/Backgrounds/angel.png"
