general {
    before_sleep_cmd = bash ~/.config/hypr/scripts/save-float-state.sh && (pidof hyprlock || hyprlock)
    after_sleep_cmd = hyprctl dispatch dpms on && bash ~/.config/hypr/scripts/restore-float-state.sh && openrgb --profile Ares
}

listener {
    timeout = 120
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
